# Generated by Django 5.0.14 on 2025-04-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrendaM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Talla', models.CharField(max_length=3)),
                ('color', models.CharField(max_length=20)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
