# Generated by Django 5.0.14 on 2025-04-22 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAppDjango', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prendam',
            old_name='Talla',
            new_name='talla',
        ),
    ]
