# Generated by Django 5.0.14 on 2025-04-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAppDjango', '0002_rename_talla_prendam_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='prendam',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
